---
title: "2017 Repair dental restorations"
author: Sergio Uribe
date: "`r format(Sys.time(), '%d %B, %Y')`"

output: 
  html_notebook: 
    toc: yes
    toc_float: true
    fig_caption: true
---


# Paquetes
```{r, include = F, echo = F}
Packages <- c("tidyverse", "forcats", "stringr", "broom", "meta")
}lapply(Packages, library, character.only = TRUE)
rm(Packages)
```

Otros paquetes
ggplotAssist
dplyrAssist
funModeling 


ver https://livebook.datascienceheroes.com/

Plots
```{r, include = F, echo = F}
install.packages("devtools")

devtools::install_github("gertstulp/ggplotgui")



library("ggplotgui")
```



# Dataset

```{r}
df <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRSKuBlcQTVJK2fZyZ4Nvf4SwSqVrxcfAGhNhl6dWHU9W39oppE4Pl4lcPy-0CRGRTqQQ0IHwFgfrY8/pub?gid=0&single=true&output=csv")
```

## Data cleaning
```{r}
glimpse(df)
```
Clean dataset from empty rows, strange symbols, etc
```{r}

df <- df %>% filter(str_detect(df$Comparison, "vs"), 
                      trimws(EvA) != "", 
                    !str_detect(EvA, "\\?"), 
                    !str_detect(EvA, "%") )



```
Select only relevant columns
```{r}
df <- df %>% select(Comparison:Outcome) %>% 
  select(-quality)
```

create a new column id

```{r}
df <-  mutate(df, id = paste(firstAuthor, year, sep = ", "))
```

## Dataset clean
```{r}
glimpse(df)
colnames(df)[7] <- "N_A" # change name col NA.
df$EvA <- as.numeric(df$EvA)
df$N_A <- as.numeric(df$N_A)
df


```



# Meta-Analysis
```{r}
meta1 <- metabin(EvA, NA., EvB, NB,
                 data = df,
                 # subset = c(41,47,51,59), 
                 studlab = paste(firstAuthor, year),
                 sm="RR", method="I")
```


# Citas

```{r}
citation()
citation(package = "tidyverse")
citation(package = "stringr")
citation(package = "broom")
citation(package = "editData")
```